# Generated by Django 6.0.2 on 2026-02-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_liveclass'),
        ('courses', '0004_alter_course_course_code'),
    ]

    operations = [
    ]
