# Generated by Django 6.0.2 on 2026-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline_notified',
            field=models.BooleanField(default=False),
        ),
    ]
