# Generated by Django 6.0.2 on 2026-03-27 17:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('live_class', 'student')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_join_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='join_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present (On Time)'), ('late', 'Present (Late)')], default='present', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='joined_at',
        ),
    ]
