# Generated by Django 6.0.2 on 2026-03-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
